version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-native-render-html
    versions:
    - 5.0.1
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jest-expo
    versions:
    - 34.0.1
